In [1]:
import numpy as np

In [4]:
arr = np.arange(11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

###Universal functions are basic functions that you can apply to every value an array.

In [5]:
np.sqrt(arr)

array([ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
        2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
        3.16227766])

In [6]:
np.exp(arr)

array([  1.00000000e+00,   2.71828183e+00,   7.38905610e+00,
         2.00855369e+01,   5.45981500e+01,   1.48413159e+02,
         4.03428793e+02,   1.09663316e+03,   2.98095799e+03,
         8.10308393e+03,   2.20264658e+04])

In [12]:
A = np.random.randn(10)
A

array([ 0.09299642, -0.42246238, -0.23707741, -0.78583423, -0.00588833,
       -1.04112355,  0.29553624, -0.95393708,  1.5752636 , -0.28394941])

In [11]:
B = np.random.randn(10)
B

array([-1.10785095, -1.00155404,  1.20476595,  0.6814443 ,  0.15744053,
        0.67420713,  0.02090207,  1.16092325, -1.08437388, -1.3070811 ])

In [15]:
# Binary Functions
np.add(A,B)

array([-1.01485453, -1.42401642,  0.96768855, -0.10438993,  0.1515522 ,
       -0.36691642,  0.31643831,  0.20698617,  0.49088972, -1.59103052])

In [16]:
np.maximum(A,B)

array([ 0.09299642, -0.42246238,  1.20476595,  0.6814443 ,  0.15744053,
        0.67420713,  0.29553624,  1.16092325,  1.5752636 , -0.28394941])

In [19]:
np.minimum(A,B)

array([-1.10785095, -1.00155404, -0.23707741, -0.78583423, -0.00588833,
       -1.04112355,  0.02090207, -0.95393708, -1.08437388, -1.3070811 ])

In [20]:
website = "http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs"
import webbrowser
webbrowser.open(website)

True

In [22]:
#LINK FOR ALL THE UNIVERSAL ARRAY FUNCTIONS ON THAT LINK!
print "URL: ", website

URL:  http://docs.scipy.org/doc/numpy/reference/ufuncs.html#available-ufuncs
